name: setup-tests-linter
on: [push]
jobs:
  what-i-was-asked-to-do:
    runs-on: ubuntu-latest

    steps:
    - name: cloning-repository
      uses: actions/checkout@v3

    - name: using-setup
      run: make setup
    - run: make start

    - name: run-tests
      run: make test

    - name: run-linter
      run: make lint  