name: setup-tests-linter
on: [push]
jobs:
  what-i-was-asked-to-do:
    runs-on: ubuntu-latest

    steps:
    - name: cloning-repository
      uses: actions/checkout@v3

    - name: setup-node-cache
      uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'npm'

    - name: using-setup
      run: make setup

    - name: run-tests
      run: make test

    - name: run-linter
      run: make lint

    - name: run-Snyk
      uses: snyk/actions/node@master
      env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}