name: setup-tests-linter
on: [push]
jobs:
  what-i-was-asked-to-do:
    runs-on: ubuntu-latest

    steps:
    - name: using-setup
      run: make setup

    - name: run-tests
      run: make test

    - name: run-linter
      run: make lint  